<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{dda73309-53de-02f8-1325-69de66ef1770}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	GoGoAxis1 : TestAxis1;
	GoGoAxis2 : TestAxis2;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[GoGoAxis1();
GoGoAxis2.CyclicLogic();
GoGoAxis2.MoveAxis();







]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="1042" Count="0" />
      <LineId Id="1041" Count="0" />
      <LineId Id="1047" Count="0" />
      <LineId Id="944" Count="1" />
      <LineId Id="927" Count="4" />
      <LineId Id="14" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>