<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="SAFETY" Id="{9a2e6223-27b0-0fcb-2a70-9980b1757f46}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM SAFETY
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="SAFETY">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>